### ISSUE TITLE
Cannot run on the varmisuse task

### ISSUE THREAD

**Issue by shangqing-liu** [microsoft/ptgnn#11]
Hi,

Thanks for this wonderful work, it is really helpful for others. But when I test for the varmisuse task, it cannot run correctly. Even in the first step. May I ask for help?
![image](https://user-images.githubusercontent.com/22492462/113095650-67093000-9226-11eb-80ef-8a91848e7c99.png)

Thanks

**Comment by shangqing-liu** [comment]
fixed

**Comment by DylanSand** [comment]
What did you do to solve this?

**Comment by Cglasses** [comment]
I encountered the same issue. May I ask how you resolved it?
