### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [microsoft/ptgnn#14]
### Describe the new feature:

It would be great to have a conda recipe so that it can be included with projects that have more complicated build processes (for example, using libraries that need C/C++ compilers).

### What is the current outcome? 

Have a recipe for `ptgnn` on the conda-forge channel.

### Is it backward-compatible? 

Yes, and it would be forward-compatible as well, because the conda bots can automatically fetch new sdists pushed to pypi.

**Comment by sarthakpati** [comment]
I am happy to work on this, BTW.

**Comment by mallamanis** [comment]
I don't have any experience with conda packages, but if you can submit a PR on this, I'd be happy to review/merge it 🚀

**Comment by sarthakpati** [comment]
Apologies, I got a bit side-tracked with other stuff and getting the dependencies on the conda-forge channel. Anyway, the recipe is ready to be merged once the conda-forge maintainers review: https://github.com/conda-forge/staged-recipes/pull/17623

**Comment by mallamanis** [comment]
Thanks a lot for this!

**Comment by sarthakpati** [comment]
Recipe is now merged, and I have added a PR: https://github.com/microsoft/ptgnn/pull/22 

Happy to include (or replace me entirely) whomever you need as a maintainer for the recipe.
